# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/nightwalkerhea/Desktop/cva6/corev_apu/fpga/xilinx/axi_dwidth_converter_64_128/axi_dwidth_converter_64_128.srcs/sources_1/ip/axi_dwidth_converter_64_128/axi_dwidth_converter_64_128.xci
# IP: The module: 'axi_dwidth_converter_64_128' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/nightwalkerhea/Desktop/cva6/corev_apu/fpga/xilinx/axi_dwidth_converter_64_128/axi_dwidth_converter_64_128.srcs/sources_1/ip/axi_dwidth_converter_64_128/axi_dwidth_converter_64_128_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_dwidth_converter_64_128'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/nightwalkerhea/Desktop/cva6/corev_apu/fpga/xilinx/axi_dwidth_converter_64_128/axi_dwidth_converter_64_128.srcs/sources_1/ip/axi_dwidth_converter_64_128/axi_dwidth_converter_64_128_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_dwidth_converter_64_128'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/nightwalkerhea/Desktop/cva6/corev_apu/fpga/xilinx/axi_dwidth_converter_64_128/axi_dwidth_converter_64_128.srcs/sources_1/ip/axi_dwidth_converter_64_128/axi_dwidth_converter_64_128.xci
# IP: The module: 'axi_dwidth_converter_64_128' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/nightwalkerhea/Desktop/cva6/corev_apu/fpga/xilinx/axi_dwidth_converter_64_128/axi_dwidth_converter_64_128.srcs/sources_1/ip/axi_dwidth_converter_64_128/axi_dwidth_converter_64_128_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_dwidth_converter_64_128'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/nightwalkerhea/Desktop/cva6/corev_apu/fpga/xilinx/axi_dwidth_converter_64_128/axi_dwidth_converter_64_128.srcs/sources_1/ip/axi_dwidth_converter_64_128/axi_dwidth_converter_64_128_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_dwidth_converter_64_128'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
